// configure notification type constants (matches server)
const constants = {
  0: 'NEW_CHILD_BRANCH_REQUEST',
  1: 'CHILD_BRANCH_REQUEST_ANSWERED',
  2: 'BRANCH_MOVED',
  3: 'MODERATOR',
  4: 'COMMENT',
  5: 'POST_FLAGGED',
  6: 'POST_REMOVED',
  7: 'POST_TYPE_CHANGED',
  8: 'POST_MARKED_NSFW',
  NEW_CHILD_BRANCH_REQUEST: 0,
  CHILD_BRANCH_REQUEST_ANSWERED: 1,
  BRANCH_MOVED: 2,
  MODERATOR: 3,
  COMMENT: 4,
  POST_FLAGGED: 5,
  POST_REMOVED: 6,
  POST_TYPE_CHANGED: 7,
  POST_MARKED_NSFW: 8,
};

export default constants;
